services:
  db:
    image: postgres:15
    container_name: dms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  documentmanagementsystem.api:
    build:
      context: .
      dockerfile: DocumentManagementSystem.API/Dockerfile
    container_name: dms-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dmsdb;Username=postgres;Password=postgres

volumes:
  pgdata:
